import { DotField } from "@/components/effects/DotField";
import { SpotlightCard } from "@/components/effects/SpotlightCard";
import { CountUp } from "@/components/effects/CountUp";
import { TextPressure } from "@/components/effects/TextPressure";
import { SplitText } from "@/components/effects/SplitText";
import { MagicBento } from "@/components/effects/MagicBento";
import DocsClient from "./DocsClient";
import { BookOpen, Sparkles, Database, Brain, HelpCircle, Shield, Mail, Bug, Lightbulb, ChevronRight } from "lucide-react";

export const metadata = {
  title: "Docs & Help",
  description: "Complete documentation, FAQ, and guides for SkillVerse."
};

const SECTIONS = [
  {
    id: "getting-started",
    title: "Getting Started",
    icon: "Sparkles",
    
    content: [
      "SkillVerse is an AI-powered analytics platform built for Screen2Skill 2026.",
      "It analyses how 250+ Indian teenagers use screens for learning, and gives you tools to explore the data yourself.",
      "Start with the **Dashboard** to see the headline numbers, or take the **Survey** to add your own data.",
      "Use the **AI Hub** for personalised analysis, and the **Workspace** to upload your own CSV."
    ]
  },
  {
    id: "survey-guide",
    title: "Survey Guide",
    icon: "BookOpen",
    
    content: [
      "Our 8-step survey takes about 3-4 minutes to complete.",
      "All responses are anonymous. We never ask for your name, email, or phone number.",
      "You can skip questions you're not comfortable answering.",
      "After submitting, you'll see a personalised 4-week learning pathway."
    ]
  },
  {
    id: "dashboard-tour",
    title: "Dashboard Tour",
    icon: "Database",
    
    content: [
      "**KPI cards** at the top show headline numbers (total students, avg screen time, AI usage, positive impact).",
      "**Charts** break down data by platform, skill, age, and city.",
      "**Insights panel** on the right is generated by Gemini based on current filters.",
      "Click any chart slice to filter the rest of the dashboard."
    ]
  },
  {
    id: "ai-hub-guide",
    title: "AI Hub Guide",
    icon: "Brain",
    
    content: [
      "**SkillBot** — Chat with our AI learning companion for personalised advice.",
      "**Wellness Analyzer** — Paste any text to get a digital wellness score.",
      "**Skill Pathway** — Get a 4-week learning plan for any skill.",
      "**Content Scorer** — Rate any YouTube channel or app for educational value.",
      "**Report Writer** — Generate a research report from a topic.",
      "**Trend Predictor** — Discover rising trends in teen screen time.",
      "**Translator** — Translate any text to 8+ languages.",
      "**Data Analyst** — Ask questions in plain English about our dataset."
    ]
  },
  {
    id: "workspace-guide",
    title: "Workspace Guide (CSV Upload)",
    icon: "Database",
    
    content: [
      "The Workspace lets you analyse your own CSV data with the same AI we use internally.",
      "**Step 1:** Drag-and-drop a CSV (max 10MB). Or click one of the sample datasets to try it first.",
      "**Step 2:** We auto-detect column types (numeric, categorical, date).",
      "**Step 3:** Auto-generated histograms + bar charts appear instantly.",
      "**Step 4:** Click **Generate Insights** to get a Gemini-powered summary.",
      "**Step 5:** Export your filtered data to CSV, or copy insights as markdown.",
      "Your data is processed locally + sent to Gemini. We do NOT store your CSV."
    ]
  },
  {
    id: "faq",
    title: "FAQ",
    icon: "HelpCircle",
    
    content: [
      "**Is SkillVerse free?** Yes, 100% free. No login required.",
      "**Who built it?** 4 students from Colonel's Central Academy, Gurugram.",
      "**Where does the data come from?** 250+ real survey responses from Indian teens + 4 public datasets.",
      "**Is my survey response private?** Yes. We store it anonymously and never share with third parties.",
      "**Which AI model do you use?** Google Gemini 2.5 Flash.",
      "**Can I download the data?** Yes — see the Reports page or the SUBMISSION_PACK folder.",
      "**How do I report a bug?** Email anujphulera@gmail.com or use the link in the footer."
    ]
  },
  {
    id: "privacy",
    title: "Privacy & Data",
    icon: "Shield",
    
    content: [
      "**Anonymous by design** — No names, emails, or phone numbers are ever collected.",
      "**Device fingerprint** — Used only to prevent duplicate survey submissions. Hashed, not reversible.",
      "**CSV uploads** — Processed in your browser + sent to Gemini API. We do NOT store your CSV.",
      "**Cookies** — Only essential ones (theme, accessibility settings). No tracking.",
      "**Open source** — All code is open source on GitHub. You can audit everything."
    ]
  },
  {
    id: "contact",
    title: "Contact",
    icon: "Mail",
    color: "from-primary to-accent",
    content: [
      "**Team Lead:** Anuj Phulera",
      "**Email:** anujphulera@gmail.com",
      "**School:** Colonel's Central Academy, Gurugram",
      "**Competition:** Screen2Skill 2026 — Techbuzz"
    ]
  },
  {
    id: "report-bug",
    title: "Report a Bug",
    icon: "Bug",
    
    content: [
      "Found something broken? Tell us!",
      "**Email:** anujphulera@gmail.com (subject: 'SkillVerse Bug')",
      "**GitHub:** github.com/UCHIHA-MADARA-ANUJ/S2S/issues",
      "Please include: page URL, what you clicked, what happened, what you expected."
    ]
  },
  {
    id: "suggest-feature",
    title: "Suggest a Feature",
    icon: "Lightbulb",
    color: "from-secondary to-primary",
    content: [
      "We'd love to hear your ideas!",
      "**Email:** anujphulera@gmail.com (subject: 'SkillVerse Feature Idea')",
      "**GitHub:** github.com/UCHIHA-MADARA-ANUJ/S2S/issues/new",
      "All serious suggestions will be considered for the next update."
    ]
  }
];

export default function DocsPage() {
  return (
    <div>
      <section className="relative min-h-[50vh] flex items-center justify-center overflow-hidden pt-24 pb-12" data-reveal>
        <div className="absolute inset-0 z-0">
          <DotField dotSpacing={20} cursorRadius={200} sparkle bulgeStrength={20} />
        </div>
        <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 w-full text-center">
          <p className="label mb-4">DOCUMENTATION · HELP · FAQ</p>
          <div style={{ minHeight: 100 }}>
            <TextPressure
              text="How can we help?"
              className="font-display font-black leading-[0.95] tracking-tight text-3xl sm:text-5xl md:text-7xl"
              minScale={0.85}
              maxScale={1.05}
            />
          </div>
          <div className="mt-6 max-w-2xl mx-auto text-text-secondary text-lg">
            <SplitText
              text="Search-friendly docs. Every section is here: from getting started, to advanced AI features, to privacy and contact."
              splitType="words"
              delay={30}
              duration={0.6}
            />
          </div>
          <div className="mt-10 grid grid-cols-2 md:grid-cols-4 gap-3 max-w-3xl mx-auto" data-reveal>
            <SpotlightCard>
              <div className="text-3xl font-display font-black text-primary"><CountUp to={SECTIONS.length} /></div>
              <div className="label mt-1">Sections</div>
            </SpotlightCard>
            <SpotlightCard>
              <div className="text-3xl font-display font-black text-accent">100%</div>
              <div className="label mt-1">Free</div>
            </SpotlightCard>
            <SpotlightCard>
              <div className="text-3xl font-display font-black text-success">0</div>
              <div className="label mt-1">Trackers</div>
            </SpotlightCard>
            <SpotlightCard>
              <div className="text-3xl font-display font-black text-secondary">8</div>
              <div className="label mt-1">AI Tools</div>
            </SpotlightCard>
          </div>
        </div>
      </section>

      <section className="px-4 sm:px-6 lg:px-8 pb-16 max-w-7xl mx-auto">
        <DocsClient sections={SECTIONS} />
      </section>
    </div>
  );
}
