"use client";
import { useState, useRef, useCallback, useMemo } from "react";
import { Upload, FileText, Sparkles, Loader2, Download, X, ChevronUp, ChevronDown, Search, BarChart3, TrendingUp, Lightbulb, AlertCircle, Link2, RefreshCw } from "lucide-react";
import { useDropzone } from "react-dropzone";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line, ScatterChart, Scatter } from "recharts";
import { toast } from "sonner";
import { parseCSV, exportToCSV, generateSampleCSV } from "@/lib/workspace/csv";
import { useWorkspace, type ColumnMeta, type Insights } from "@/lib/workspace/store";
import { DotField } from "@/components/effects/DotField";
import { trackEvent } from "@/components/ui/Celebration";
import { SpotlightCard } from "@/components/effects/SpotlightCard";
import { CountUp } from "@/components/effects/CountUp";
import { MagicRings } from "@/components/effects/MagicRings";
import { GlowCard } from "@/components/effects/GlowCard";

export default function WorkspacePage() {
  const {
    fileName, data, columns, insights, loadingInsights, filters, sortBy, searchQuery,
    setFile, setInsights, setLoadingInsights, setFilter, clearFilter, setSort, setSearch, clear
  } = useWorkspace();

  const onDrop = useCallback(async (acceptedFiles: File[]) => {
    const file = acceptedFiles[0];
    if (!file) return;
    if (file.size > 10 * 1024 * 1024) { toast.error("File too large (max 10MB)"); return; }
    if (!file.name.toLowerCase().endsWith(".csv")) { toast.error("Only CSV files accepted"); return; }
    try {
      const { data, columns } = await parseCSV(file);
      setFile(file.name, data, columns); trackEvent("csvUploaded", true);
      toast.success(`Loaded ${data.length} rows · ${columns.length} columns`);
      fetchInsights(data, columns);
    } catch (e: any) { toast.error("Failed to parse CSV: " + e.message); }
  }, []);

  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    onDrop, accept: { "text/csv": [".csv"] }, multiple: false
  });

  const fetchInsights = async (data: any[], columns: ColumnMeta[]) => {
    setLoadingInsights(true);
    try {
      const res = await fetch("/api/csv-insights", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ data: data.slice(0, 50), columns: columns.map(c => ({ name: c.name, type: c.type })) })
      });
      const result = await res.json();
      if (result.success && result.insights) { setInsights(result.insights); toast.success("AI insights ready"); }
      else { toast.error("Failed to get insights: " + (result.error || "Unknown")); }
    } catch (e: any) { toast.error("Failed: " + e.message); }
    finally { setLoadingInsights(false); }
  };

  const trySample = (type: "grades" | "sales" | "survey") => {
    const { name, csv } = generateSampleCSV(type);
    const blob = new Blob([csv], { type: "text/csv" });
    const file = new File([blob], name, { type: "text/csv" });
    onDrop([file]);
  };

  const exportData = () => {
    if (!data.length) return;
    exportToCSV(data, fileName || "export.csv");
    toast.success("CSV downloaded");
  };

  const exportInsights = () => {
    if (!insights) return;
    const text = `# AI Insights for ${fileName}\n\n## Summary\n${insights.summary}\n\n## Key Trends\n${insights.keyTrends.map((t, i) => `${i + 1}. ${t}`).join("\n")}\n\n## Outliers\n${insights.outliers.map((o, i) => `${i + 1}. ${o}`).join("\n")}\n\n## Correlations\n${insights.correlations.map((c, i) => `${i + 1}. ${c}`).join("\n")}\n\n## Recommendations\n${insights.recommendations.map((r, i) => `${i + 1}. ${r}`).join("\n")}\n\nGenerated by SkillVerse AI\n`;
    const blob = new Blob([text], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${fileName.replace(".csv", "")}-insights.md`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Insights downloaded");
  };

  return (
    <div className="relative min-h-screen pt-24 pb-12 px-4 sm:px-6 lg:px-8 overflow-hidden">
      <div className="absolute inset-0 z-0 opacity-50">
        <DotField dotSpacing={24} cursorRadius={220} sparkle={false} />
      </div>

      <div className="relative z-10 max-w-7xl mx-auto">
        <div className="text-center mb-8">
          <p className="label mb-2">NEW FEATURE</p>
          <h1 className="font-display font-black text-4xl sm:text-6xl tracking-tighter mb-2">Workspace.</h1>
          <p className="text-text-secondary max-w-2xl mx-auto">
            Upload your CSV. Get instant AI insights and auto-generated charts. No login. No data leaves your browser.
          </p>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-8">
          <SpotlightCard>
            <div className="text-2xl font-display font-black"><CountUp to={data.length || 0} /></div>
            <div className="label mt-1">Rows</div>
          </SpotlightCard>
          <SpotlightCard>
            <div className="text-2xl font-display font-black"><CountUp to={columns.length || 0} /></div>
            <div className="label mt-1">Columns</div>
          </SpotlightCard>
          <SpotlightCard>
            <div className="text-2xl font-display font-black"><CountUp to={columns.filter(c => c.type === "numeric").length || 0} /></div>
            <div className="label mt-1">Numeric</div>
          </SpotlightCard>
          <SpotlightCard>
            <div className="text-2xl font-display font-black"><CountUp to={columns.filter(c => c.type === "categorical").length || 0} /></div>
            <div className="label mt-1">Categorical</div>
          </SpotlightCard>
        </div>

        {!data.length ? (
          <div>
            <div
              {...getRootProps()}
              role="button"
              tabIndex={0}
              aria-label="Upload CSV file. Drag and drop a CSV file here, or press Enter to browse for a file."
              className={`relative border-2 border-dashed rounded-3xl p-12 text-center cursor-pointer transition-all focus-visible:border-primary ${isDragActive ? "border-primary bg-primary/10" : "border-white/20 hover:border-primary/50"}`}
            >
              <input {...getInputProps()} />
              <Upload className="w-12 h-12 text-primary mx-auto mb-4" />
              <p className="text-text-primary font-display font-bold text-xl mb-2">
                {isDragActive ? "Drop your CSV here" : "Drag & drop your CSV"}
              </p>
              <p className="text-text-muted text-sm mb-6">or click to browse · max 10MB</p>
              <div className="flex gap-2 justify-center flex-wrap">
                <button onClick={(e) => { e.stopPropagation(); trySample("grades"); }} className="glass px-3 py-1.5 rounded-lg text-xs text-text-secondary hover:text-white">
                  Try Student Grades (100 rows)
                </button>
                <button onClick={(e) => { e.stopPropagation(); trySample("sales"); }} className="glass px-3 py-1.5 rounded-lg text-xs text-text-secondary hover:text-white">
                  Try Sales Data (50 rows)
                </button>
                <button onClick={(e) => { e.stopPropagation(); trySample("survey"); }} className="glass px-3 py-1.5 rounded-lg text-xs text-text-secondary hover:text-white">
                  Try Survey Results (200 rows)
                </button>
              </div>
            </div>
            <p className="text-center text-text-muted text-xs mt-4">
              🔒 Data is processed locally + AI is queried via Gemini (no data stored)
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
            <DataTablePanel />
            <ChartsPanel />
            <InsightsPanel
              insights={insights}
              loading={loadingInsights}
              onRefresh={() => fetchInsights(data, columns)}
              fileName={fileName}
              onClear={clear}
              onExportData={exportData}
              onExportInsights={exportInsights}
            />
          </div>
        )}
      </div>
    </div>
  );
}

function DataTablePanel() {
  const { data, columns, filters, sortBy, searchQuery, setFilter, clearFilter, setSort, setSearch } = useWorkspace();
  const filtered = useMemo(() => {
    let rows = data;
    if (searchQuery) {
      const q = searchQuery.toLowerCase();
      rows = rows.filter(r => Object.values(r).some(v => String(v).toLowerCase().includes(q)));
    }
    Object.entries(filters).forEach(([col, val]) => {
      if (val) rows = rows.filter(r => String(r[col]) === val);
    });
    if (sortBy) {
      rows = [...rows].sort((a, b) => {
        const av = a[sortBy.column], bv = b[sortBy.column];
        if (av == null) return 1; if (bv == null) return -1;
        const cmp = av < bv ? -1 : av > bv ? 1 : 0;
        return sortBy.direction === "asc" ? cmp : -cmp;
      });
    }
    return rows;
  }, [data, filters, sortBy, searchQuery]);

  return (
    <div className="glass p-4 flex flex-col h-[500px] sm:h-[600px] lg:h-[700px]">
      <div className="flex items-center justify-between mb-3">
        <h3 className="font-display font-bold text-sm flex items-center gap-2">
          <FileText className="w-4 h-4 text-primary" /> Data
        </h3>
        <span className="text-xs text-text-muted">{filtered.length} of {data.length} rows</span>
      </div>
      <div className="flex gap-2 mb-3">
        <div className="relative flex-1">
          <Search className="w-3 h-3 absolute left-2 top-1/2 -translate-y-1/2 text-text-muted" />
          <input value={searchQuery} onChange={e => setSearch(e.target.value)} placeholder="Search..." className="w-full bg-surface border border-white/10 rounded pl-7 pr-2 py-1.5 text-xs text-white focus:outline-none focus:border-primary" />
        </div>
        {Object.keys(filters).length > 0 && (
          <button onClick={clearFilter} className="text-xs text-text-muted hover:text-white px-2">Clear</button>
        )}
      </div>
      <div className="flex-1 overflow-auto">
        <table className="w-full text-xs">
          <thead className="sticky top-0 bg-surface/90 backdrop-blur z-10">
            <tr>
              {columns.map(c => (
                <th key={c.name} className="text-left p-2 font-mono text-text-muted border-b border-white/5">
                  <button
                    onClick={() => setSort(sortBy?.column === c.name ? (sortBy.direction === "asc" ? { column: c.name, direction: "desc" } : null) : { column: c.name, direction: "asc" })}
                    className="flex items-center gap-1 hover:text-white"
                  >
                    {c.name}
                    {sortBy?.column === c.name && (sortBy.direction === "asc" ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />)}
                  </button>
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {filtered.slice(0, 200).map((row, i) => (
              <tr key={i} className="border-b border-white/5 hover:bg-white/5">
                {columns.map(c => (
                  <td key={c.name} className="p-2 text-text-secondary whitespace-nowrap">
                    {c.type === "categorical" && !filters[c.name] ? (
                      <select
                        value={filters[c.name] || ""}
                        onChange={e => setFilter(c.name, e.target.value)}
                        className="bg-transparent text-xs border-none focus:outline-none cursor-pointer"
                      >
                        <option value="">{String(row[c.name] ?? "")}</option>
                        {Array.from(new Set(data.map(r => String(r[c.name])))).filter(v => v).slice(0, 50).map(v => (
                          <option key={v} value={v}>{v}</option>
                        ))}
                      </select>
                    ) : (
                      <span>{String(row[c.name] ?? "")}</span>
                    )}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
        {filtered.length > 200 && (
          <p className="text-xs text-text-muted text-center py-2">Showing first 200 of {filtered.length}</p>
        )}
      </div>
    </div>
  );
}

function ChartsPanel() {
  const { data, columns } = useWorkspace();
  const numericCols = columns.filter(c => c.type === "numeric");
  const categoricalCols = columns.filter(c => c.type === "categorical");
  const dateCols = columns.filter(c => c.type === "date");

  return (
    <div className="glass p-4 h-[500px] sm:h-[600px] lg:h-[700px] overflow-auto">
      <h3 className="font-display font-bold text-sm mb-3 flex items-center gap-2">
        <BarChart3 className="w-4 h-4 text-primary" /> Auto Charts
      </h3>
      {numericCols.length === 0 ? (
        <p className="text-text-muted text-sm">No numeric columns to chart.</p>
      ) : (
        <div className="space-y-4">
          {numericCols.slice(0, 4).map(col => {
            const values = data.map(r => Number(r[col.name])).filter(n => !isNaN(n));
            if (!values.length) return null;
            const min = Math.min(...values);
            const max = Math.max(...values);
            const bins = 8;
            const binSize = (max - min) / bins || 1;
            const hist = Array.from({ length: bins }, (_, i) => ({
              bin: `${(min + i * binSize).toFixed(0)}-${(min + (i + 1) * binSize).toFixed(0)}`,
              count: values.filter(v => v >= min + i * binSize && v < min + (i + 1) * binSize).length
            }));
            return (
              <GlowCard key={col.name} className="p-3">
                <div className="text-xs label mb-2">{col.name} distribution</div>
                <ResponsiveContainer width="100%" height={120}>
                  <BarChart data={hist}>
                    <Bar dataKey="count" fill="#6366F1" radius={[2, 2, 0, 0]} />
                    <XAxis dataKey="bin" tick={{ fontSize: 9, fill: "#94A3B8" }} />
                    <YAxis tick={{ fontSize: 9, fill: "#94A3B8" }} />
                    <Tooltip contentStyle={{ background: "#0F172A", border: "1px solid #1E293B", fontSize: 11 }} />
                  </BarChart>
                </ResponsiveContainer>
              </GlowCard>
            );
          })}
          {categoricalCols.length > 0 && numericCols.length > 0 && (
            <GlowCard className="p-3">
              <div className="text-xs label mb-2">{categoricalCols[0].name} × {numericCols[0].name}</div>
              <ResponsiveContainer width="100%" height={150}>
                <BarChart
                  data={(() => {
                    const col = categoricalCols[0].name;
                    const num = numericCols[0].name;
                    const agg: Record<string, { sum: number; n: number }> = {};
                    data.forEach(r => {
                      const k = String(r[col]);
                      const v = Number(r[num]);
                      if (!isNaN(v)) {
                        if (!agg[k]) agg[k] = { sum: 0, n: 0 };
                        agg[k].sum += v; agg[k].n += 1;
                      }
                    });
                    return Object.entries(agg).map(([name, v]) => ({
                      name: name.length > 12 ? name.slice(0, 12) + "…" : name,
                      avg: +(v.sum / v.n).toFixed(1)
                    })).slice(0, 8);
                  })()}
                >
                  <Bar dataKey="avg" fill="#8B5CF6" radius={[2, 2, 0, 0]} />
                  <XAxis dataKey="name" tick={{ fontSize: 9, fill: "#94A3B8" }} />
                  <YAxis tick={{ fontSize: 9, fill: "#94A3B8" }} />
                  <Tooltip contentStyle={{ background: "#0F172A", border: "1px solid #1E293B", fontSize: 11 }} />
                </BarChart>
              </ResponsiveContainer>
            </GlowCard>
          )}
          {dateCols.length > 0 && numericCols.length > 0 && (
            <GlowCard className="p-3">
              <div className="text-xs label mb-2">{numericCols[0].name} over time</div>
              <ResponsiveContainer width="100%" height={150}>
                <LineChart
                  data={(() => {
                    const dateCol = dateCols[0].name;
                    const numCol = numericCols[0].name;
                    const agg: Record<string, { sum: number; n: number }> = {};
                    data.forEach(r => {
                      const d = new Date(r[dateCol]);
                      if (isNaN(d.getTime())) return;
                      const k = d.toISOString().split("T")[0];
                      const v = Number(r[numCol]);
                      if (!isNaN(v)) {
                        if (!agg[k]) agg[k] = { sum: 0, n: 0 };
                        agg[k].sum += v; agg[k].n += 1;
                      }
                    });
                    return Object.entries(agg).map(([date, v]) => ({
                      date, value: +(v.sum / v.n).toFixed(1)
                    })).sort((a, b) => a.date.localeCompare(b.date)).slice(0, 20);
                  })()}
                >
                  <Line type="monotone" dataKey="value" stroke="#06B6D4" strokeWidth={2} dot={false} />
                  <XAxis dataKey="date" tick={{ fontSize: 9, fill: "#94A3B8" }} />
                  <YAxis tick={{ fontSize: 9, fill: "#94A3B8" }} />
                  <Tooltip contentStyle={{ background: "#0F172A", border: "1px solid #1E293B", fontSize: 11 }} />
                </LineChart>
              </ResponsiveContainer>
            </GlowCard>
          )}
          {numericCols.length >= 2 && (
            <GlowCard className="p-3">
              <div className="text-xs label mb-2">{numericCols[0].name} vs {numericCols[1].name}</div>
              <ResponsiveContainer width="100%" height={150}>
                <ScatterChart>
                  <Scatter
                    data={data.slice(0, 100).map(r => ({
                      x: Number(r[numericCols[0].name]),
                      y: Number(r[numericCols[1].name])
                    })).filter(p => !isNaN(p.x) && !isNaN(p.y))}
                    fill="#EC4899"
                  />
                  <XAxis dataKey="x" type="number" tick={{ fontSize: 9, fill: "#94A3B8" }} />
                  <YAxis dataKey="y" type="number" tick={{ fontSize: 9, fill: "#94A3B8" }} />
                  <Tooltip contentStyle={{ background: "#0F172A", border: "1px solid #1E293B", fontSize: 11 }} cursor={{ strokeDasharray: "3 3" }} />
                </ScatterChart>
              </ResponsiveContainer>
            </GlowCard>
          )}
        </div>
      )}
    </div>
  );
}

function InsightsPanel({ insights, loading, onRefresh, fileName, onClear, onExportData, onExportInsights }: {
  insights: Insights | null;
  loading: boolean;
  onRefresh: () => void;
  fileName: string;
  onClear: () => void;
  onExportData: () => void;
  onExportInsights: () => void;
}) {
  return (
    <div className="glass p-4 h-[500px] sm:h-[600px] lg:h-[700px] overflow-auto">
      <div className="flex items-center justify-between mb-3">
        <h3 className="font-display font-bold text-sm flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-primary" /> AI Insights
        </h3>
        <div className="flex gap-1">
          {insights && <button onClick={onRefresh} className="text-text-muted hover:text-white p-1" title="Refresh"><RefreshCw className="w-3 h-3" /></button>}
          <button onClick={onClear} className="text-text-muted hover:text-error p-1" title="Clear"><X className="w-3 h-3" /></button>
        </div>
      </div>

      {loading ? (
        <div className="text-center py-12">
          <div className="relative inline-block">
            <MagicRings rings={3} size={120} />
            <Loader2 className="w-6 h-6 text-primary animate-spin absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2" />
          </div>
          <p className="text-text-muted text-xs mt-4">Analyzing with Gemini...</p>
        </div>
      ) : !insights ? (
        <p className="text-text-muted text-sm">Insights will appear here once your CSV is loaded.</p>
      ) : (
        <div className="space-y-3">
          <div>
            <div className="label mb-1 flex items-center gap-1"><Sparkles className="w-3 h-3" /> Summary</div>
            <p className="text-text-secondary text-xs leading-relaxed">{insights.summary}</p>
          </div>
          {insights.keyTrends.length > 0 && (
            <div>
              <div className="label mb-1 flex items-center gap-1"><TrendingUp className="w-3 h-3" /> Key Trends</div>
              <ul className="space-y-1">
                {insights.keyTrends.map((t, i) => (
                  <li key={i} className="text-xs text-text-secondary flex gap-2"><span className="text-primary">→</span> {t}</li>
                ))}
              </ul>
            </div>
          )}
          {insights.outliers.length > 0 && (
            <div>
              <div className="label mb-1 flex items-center gap-1"><AlertCircle className="w-3 h-3" /> Outliers</div>
              <ul className="space-y-1">
                {insights.outliers.map((o, i) => (
                  <li key={i} className="text-xs text-text-secondary flex gap-2"><span className="text-warning">⚡</span> {o}</li>
                ))}
              </ul>
            </div>
          )}
          {insights.correlations.length > 0 && (
            <div>
              <div className="label mb-1 flex items-center gap-1"><Link2 className="w-3 h-3" /> Correlations</div>
              <ul className="space-y-1">
                {insights.correlations.map((c, i) => (
                  <li key={i} className="text-xs text-text-secondary flex gap-2"><span className="text-accent">⇄</span> {c}</li>
                ))}
              </ul>
            </div>
          )}
          {insights.recommendations.length > 0 && (
            <div>
              <div className="label mb-1 flex items-center gap-1"><Lightbulb className="w-3 h-3" /> Recommendations</div>
              <ul className="space-y-1">
                {insights.recommendations.map((r, i) => (
                  <li key={i} className="text-xs text-text-secondary flex gap-2"><span className="text-success">✓</span> {r}</li>
                ))}
              </ul>
            </div>
          )}
          <div className="flex gap-2 pt-3 border-t border-white/10">
            <button onClick={onExportData} className="flex-1 glass px-3 py-1.5 rounded text-xs text-text-secondary hover:text-white flex items-center justify-center gap-1">
              <Download className="w-3 h-3" /> CSV
            </button>
            <button onClick={onExportInsights} className="flex-1 glass px-3 py-1.5 rounded text-xs text-text-secondary hover:text-white flex items-center justify-center gap-1">
              <Download className="w-3 h-3" /> Insights
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
